### ISSUE TITLE
No frequency or height config?

### ISSUE THREAD

**Issue by Darkere** [AlasDiablo/JANOEO#1]
I cannot find a config that sets how much or where to generate the ores. Just an enable/disable option. This seems like a rather large oversight... Any plans to add something like that?

**Comment by AlasDiablo** [comment]
Hello, it normal to not found it, because in the config file you can juste enable it or disable it.
But i can add it in next update, if i have the time to do it.

**Comment by AlasDiablo** [comment]
I add the possibility to change frequency and height only for overworld ore for the moment.
