### ISSUE TITLE
Encounterd Error at Common_setup

### ISSUE THREAD

**Issue by JCSweetHeart** [AlasDiablo/JANOEO#12]
[bug1_jf001.pdf](https://github.com/Janoeo/Foundation/files/6982588/bug1_jf001.pdf)

**Describe the bug**
Have added Janoeo Foundation and the required Mod Jade-1.17.1-3.0.1.jar but become a Error. Using Minecraft 1.17.1 and the currently Forge (.33) - but have tested with .26/32 - momently the only avaible Forge Versions without a lot ot Search with Google ;)

**To Reproduce**
1. Starting Minecraft
2. Started with Forge .33 (currently ForgeVersion) and 39 other Mods, but there Work without your Mod.
3. Become the Error direct after the first Loading - Screen

**Expected behavior**

**Screenshots**
Screenshot see the PDF - FIle  - using Ubunutu momently and have in the short Time doesnt found a other possible Way to show your the Error.

**Minecraft information (please complete the following information):**
 - MC Version: 1.17.1
 - Janoeo Version: Janoeo+Foundation-6.6.1.74-experimental.jar
 - Jade-1.17.1-3.0.1.jar
 - Your MC Username: GamerStorm1

**Comment by AlasDiablo** [comment]
Hello ty for the report i have fix this issues in the version 6.6.2.76.
This a cause by breaking change from forge (harvest level system)
