### ISSUE TITLE
No Ore Gen in Mining Dimensions (1.16.5)

### ISSUE THREAD

**Issue by LocalBoomer** [AlasDiablo/JANOEO#19]
**Describe the bug**
Janoeo ores aren't generating in mining dimensions from other mods

**To Reproduce**
1. Install janoeo alongside a mining dimension mod (tested with JAMD and Advanced Mining Dimension)
2. Configure Janoeo ore gen ([janoeo config](https://drive.google.com/file/d/1kJqZIG4yJir03mDidhcilRom9-nmnOmc/view?usp=sharing))
3. Enter mining dimension
4. No ores = No profit

**Expected behavior**
I imagine the mining dimension mods should be able to extract the ore config/generation from janoeo and generate ores accordingly but honestly idk. Basically generate janoeo's ores

**Minecraft information (please complete the following information):**
 - MC Version: 1.16.5
 - Janoeo Version: 5.6.0.68

Tested with:
- Advanced Mining Dimension/Mining World (mininig_dimension) 1.0.6 ([link](https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension))
- JAMD/Just Another Mining Dimension (jamd) 1.2.4-build.17 ([link](https://www.curseforge.com/minecraft/mc-mods/jamd))

**Comment by AlasDiablo** [comment]
Hi, i have take a look to this but i don't see why this didn't work.
I use the forge system to add feature to the world but the biome from `jamd` and `mining_dimension`.
I have tested with other mod who add ore and some of it have the same issues.
- Forestry work only on one mod
- Mekanism same thing as Forestry but it work with the other mod

**Comment by AlasDiablo** [comment]
After testing thing to fix this problem, i'm not able to fix this issue without rewriting the world generation system.
Sorry for that, but i wont fix this issue (cause: janoeo 1.16.5 is now a old version and to much work)
