### ISSUE TITLE
JANOEO preventing world generation on 1.16 release.

### ISSUE THREAD

**Issue by papuSpartan** [AlasDiablo/JANOEO#2]
`[08Jul2020 19:55:14.753] [Render thread/ERROR] [net.minecraft.tags.TagCollection/]: Couldn't load item tag forge:ores as it is missing following references: #forge:ores/diamond (from forge-1.16.1-32.0.61-universal.jar),#forge:ores/diamond (from janoeo-3.6.jar)`

**Comment by AlasDiablo** [comment]
When i have port my mods forge have some issues with the tag, and apparently i forgot to fix some of this problem in my mod...
I look for when i have the time....

**Comment by AlasDiablo** [comment]
Problem fix here: #3 
I upload a update soon.
