### ISSUE TITLE
Crash at the startup

### ISSUE THREAD

**Issue by emanuele246gi** [AlasDiablo/JANOEO#20]
**Describe the bug**
After I updated the mod at its latest version, it crashed just at the moment it launched the game, here it is the debug.log: https://pastebin.com/UMvfqssb

I'm sure it is from this mod because I downgraded it to 3.82 and it worked fine.

**To Reproduce**
1. Update the mod 
3. Launch the game

**Minecraft information (please complete the following information):**
 - MC Version: [1.18.2]
 - Janoeo Version: [7.10.3.83]

**Comment by AlasDiablo** [comment]
Hi, did you have a crash, mod list or any more info to help me ?
A log file of 1600 line can take a lot of time to analyse…

**Comment by AlasDiablo** [comment]
One more thing, from what i see in the log file, Foundation is not quote during error, this is weird.
But i have found a potential error with mixim.

**Comment by AlasDiablo** [comment]
A continuous integration build will be available here https://github.com/Janoeo/Foundation/actions/runs/2524167428
Can you test with this version and give me feedback ?
I don't have a user environment to test and dev environment work very differently.

**Comment by emanuele246gi** [comment]
Hi, sorry for the long wait, anyway, it didn't create any crash report, so that's why I sent the debug. About the build, how can I download it? I'm not that good with Github 😅

**Comment by AlasDiablo** [comment]
Is in the Artifacts section when the build is finished.
The mod file is `Janoeo Foundation-ci.42.jar`.
https://github.com/Janoeo/Foundation/suites/6996120409/artifacts/274209229

**Comment by AlasDiablo** [comment]
Hi, again, i have publish a release on curseforge with the fix avaible in the ci build, i hope this fix the crash, i let the issue open for now

**Comment by emanuele246gi** [comment]
Thank you, I'll try this as soon as I can

**Comment by emanuele246gi** [comment]
Yep now it works! Thanks for your help man!
