### ISSUE TITLE
Osmium has no crafting recipes

### ISSUE THREAD

**Issue by jusipat** [AlasDiablo/JANOEO#8]
![image](https://user-images.githubusercontent.com/60302563/100522206-4c368a00-3166-11eb-85d4-37906f32e42c.png)
![image](https://user-images.githubusercontent.com/60302563/100522211-535d9800-3166-11eb-9875-a48540050e68.png)

JANOEO Osmium is not recognized by Mekanism making it totally useless, The Mekanism crafting recipes only recognize Mekanism osmium as an input in any crafting recipes or machines.

**Comment by jusipat** [comment]
Upon further inpection and help from the Mekanism discord I found it is due to JANEOs osmium not even being tagged. 
![image](https://user-images.githubusercontent.com/60302563/100522934-ba308080-3169-11eb-965e-7086e1a6d988.png) This is what I was told and I am wondering if this is true, and if there are any solutions asides from CraftTweaker.

**Comment by AlasDiablo** [comment]
Thank you for this report and big thank to @cflip for making a fix, i will create some thing for janoeo contributor on my mod

**Comment by AlasDiablo** [comment]
@jprik @cflip if you are on my discord what is you tag i have make 3 role `Community Contributor`, `Bug Hunter`, `Code Writer` ?
And in the same time you minecraft name (non-crark game is prefereble) ?
